# Generated by Django 4.2.3 on 2023-07-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inp', models.FileField(blank=True, default='', help_text='загрузите файл/файлы', upload_to='bin')),
            ],
        ),
    ]
